name: contextscore
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - joblib
  - bedtools
  - setuptools
  - conda-build
  - pytest
